env:
    - export SELENIUM_BROWSER=chrome
    - export SELENIUM_BROWSER=firefox
    - export SAUCE=true; export SELENIUM_BROWSER=chrome
    - export SAUCE=true; export SELENIUM_BROWSER=firefox

command:
    - make test-local
